const INTERNAL_SERVER_ERROR_CODE = 500;
const NOT_FOUND_ERROR_CODE = 404;
const BAD_REQUEST_ERROR_CODE = 400;
const CREATED_CODE = 201;

const REG_EXP = '/https?:\/\/(www\.)?[]/';

module.exports = {
  INTERNAL_SERVER_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  BAD_REQUEST_ERROR_CODE,
  CREATED_CODE,
  REG_EXP,
};
